name: Moo Template Engine
author: cooke
category: Native
tags: [template, templating, engine, html]
docs: http://mte.null-tech.com/doc.html
demo: http://mte.null-tech.com/demos.html
current: 0.3